'use strict';

module.exports = {
	Assign: require('./Assign'),
	Block: require('./Block'),
	// Catch: require('./Catch'),
	// Choice: require('./Choice'),
	// Clear: require('./Clear'),
	// Data: require('./Data'),
	// Disconnect: require('./Disconnect'),
	// Else: require('./Else'),
	// Elseif: require('./Elseif'),
	// Enumerate: require('./Enumerate'),
	// ErrorTag: require('./ErrorTag'),
	// Exit: require('./Exit'),
	// Field: require('./Field'),
	// Filled: require('./Filled'),
	Form: require('./Form'),
	// Foreach: require('./Foreach'),
	Goto: require('./Goto'),
	// Grammar: require('./Grammar'),
	// Help: require('./Help'),
	// If: require('./If'),
	// Initial: require('./Initial'),
	// Link: require('./Link'),
	// Log: require('./Log'),
	// Menu: require('./Menu'),
	// Meta: require('./Meta'),
	// Metadata: require('./Metadata'),
	// Noinput: require('./Noinput'),
	// Nomatch: require('./Nomatch'),
	// ObjectTag: require('./ObjectTag'),
	// Option: require('./Option'),
	// Param: require('./Param'),
	Prompt: require('./Prompt'),
	// Property: require('./Property'),
	// Record: require('./Record'),
	// Reprompt: require('./Reprompt'),
	// Return: require('./Return'),
	Script: require('./Script'),
	// Subdialog: require('./Subdialog'),
	// Submit: require('./Submit'),
	// Throw: require('./Throw'),
	// Transfer: require('./Transfer'),
	Value: require('./Value'),
	Var: require('./Var'),
	Vxml: require('./Vxml'),
	// // SSML Tags
	// Audio: require('./Audio'),
	// Break: require('./Break'),
	// Desc: require('./Desc'),
	// Emphasis: require('./Emphasis'),
	// Lexicon: require('./Lexicon'),
	// Mark: require('./Mark'),
	// P: require('./P'),
	// Phoneme: require('./Phoneme'),
	// Prosody: require('./Prosody'),
	// S: require('./S'),
	// Sayas: require('./Sayas'),
	// Sub: require('./Sub'),
	// Voice: require('./Voice'),
	// // SRGS Tags
	// Example: require('./Example'),
	// Item: require('./Item'),
	// Oneof: require('./Oneof'),
	// Rule: require('./Rule'),
	// Ruleref: require('./Ruleref'),
	// Tag: require('./Tag'),
	// Token: require('./Token'),
	// // Generic XML Tags
	Text: require('./Text'),
}